-- Generated by layout-editor
---@diagnostic disable: undefined-global
local UI = require("urhox-libs/UI")
local registry = require("ui_registry")
local scene2d = require("scene2d_2D瓦片庭院")
local logic = require("logic_2D瓦片庭院")
require("urhox-libs/UI/GameHUD")

-- ────────────────────────────────────────────────────────────────────────────
-- 设计分辨率: 1190×768 | 缩放策略: MatchHeight
-- 高度精确匹配设计高，横向按比例（竖版游戏）
-- 2D 场景层 (UrhoX 原生) + UI/HUD 层共存
-- ────────────────────────────────────────────────────────────────────────────

local scene_
local cameraNode

local function firstPageBuilder()
    for _, buildFn in pairs(registry) do
        if type(buildFn) == "function" then
            return buildFn
        end
    end
    return nil
end

-- 极简 HUD 回调桥：音效经 SoundSource 播放；分数/血量/计时/胜负留空钩子，
-- 项目可按需接到具体 UI 文本节点（保留接口，避免再次出现"传 nil 全无反馈"）。
local function makeGameHud()
    return {
        OnHpChange = function(hp, maxHp) end,
        OnScoreChange = function(score) end,
        OnTimerTick = function(id, sec) end,
        OnGameOver = function(result, reason) end,
        OnPlaySound = function(sound)
            local n = scene_:CreateChild("__sfx")
            local src = n:CreateComponent("SoundSource")
            src.soundType = "Effect"
            src.autoRemoveMode = REMOVE_NODE
            local s = cache:GetResource("Sound", sound)
            if s then src:Play(s) end
        end,
    }
end

function Start()
    -- ═══ 2D 场景层 ═══
    scene_ = Scene()
    scene_:CreateComponent("Octree")
    local physicsWorld = scene_:CreateComponent("PhysicsWorld2D")
    physicsWorld.gravity = Vector2(0, 0)

    -- 正交相机 + Viewport
    cameraNode = scene_:CreateChild("Camera2D")
    local camera = cameraNode:CreateComponent("Camera")
    camera.orthographic = true
    camera.orthoSize = 4.16
    cameraNode.position = Vector3(0, 0, -10)
    renderer:SetViewport(0, Viewport:new(scene_, camera))

    -- 构建 2D 场景节点 + 初始化逻辑
    local nodes = scene2d.Build(scene_)
    logic.orthoSize = camera.orthoSize
    logic.cameraNode = cameraNode

    -- ═══ UI/HUD 层（叠在 2D 场景上方） ═══
    UI.Init({
        fonts = {
            { family = "sans", weights = { normal = "Fonts/MiSans-Regular.ttf" } },
        },
        scale = function() return graphics.height / 768 end,
    })
    local buildFn = firstPageBuilder()
    if buildFn then
        UI.SetRoot(buildFn())
    end

    -- 虚拟摇杆 + 跳跃/射击按钮（GameHUD）驱动玩家
    GameHUD.Initialize()
    local hud = GameHUD.Create({ enableJump = true, enableShooter = true })
    logic.joystick = hud.joystick
    logic.jumpButton = hud.jumpButton
    logic.shootButton = hud.shootButton or hud.fireButton

    -- HUD 回调桥：把分数/血量/计时/胜负/音效接到 UI 与音频（之前传 nil，导致运行时全无反馈）。
    logic.Init(scene_, nodes, makeGameHud())

    SubscribeToEvent("Update", "HandleUpdate")
    SubscribeToEvent("PhysicsBeginContact2D", "HandleBeginContact")
    SubscribeToEvent("PhysicsEndContact2D", "HandleEndContact")
end

function HandleUpdate(eventType, eventData)
    local dt = eventData["TimeStep"]:GetFloat()
    logic.Update(dt)
end

function HandleBeginContact(eventType, eventData)
    local nodeA = eventData["NodeA"]:GetPtr("Node")
    local nodeB = eventData["NodeB"]:GetPtr("Node")
    local shapeA = eventData["ShapeA"]:GetPtr("CollisionShape2D")
    local shapeB = eventData["ShapeB"]:GetPtr("CollisionShape2D")
    logic.OnContact(nodeA, nodeB, shapeA, shapeB, true)
end

function HandleEndContact(eventType, eventData)
    local nodeA = eventData["NodeA"]:GetPtr("Node")
    local nodeB = eventData["NodeB"]:GetPtr("Node")
    local shapeA = eventData["ShapeA"]:GetPtr("CollisionShape2D")
    local shapeB = eventData["ShapeB"]:GetPtr("CollisionShape2D")
    logic.OnContact(nodeA, nodeB, shapeA, shapeB, false)
end

function Stop()
    UI.Shutdown()
end
