-- Generated by layout-editor
-- ui_HomeScreen_工坊主界面 action scaffold
local M = {}

M.handlers = {
}

function M.Dispatch(actionId, ctx)
    local handler = M.handlers[actionId]
    if handler then
        return handler(ctx)
    end
end

return M
