-- Generated by layout-editor
---@diagnostic disable: undefined-global
local UI = require("urhox-libs/UI")
local registry = require("ui_registry")

-- ────────────────────────────────────────────────────────────────────────────
-- 设计分辨率: 1366×768 | 缩放策略: MatchWidth
-- 宽度精确匹配设计宽，纵向按比例（横版游戏）
-- ────────────────────────────────────────────────────────────────────────────

local function firstPageBuilder()
    for _, buildFn in pairs(registry) do
        if type(buildFn) == "function" then
            return buildFn
        end
    end
    return nil
end

function Start()
    UI.Init({
        fonts = {
            { family = "sans", weights = { normal = "Fonts/MiSans-Regular.ttf" } },
        },
        scale = function() return graphics.width / 1366 end,
    })
    local buildFn = firstPageBuilder()
    if buildFn then
        UI.SetRoot(buildFn())
    end
end

function Stop()
    UI.Shutdown()
end
