-- Generated by layout-editor
return {
    ["doc_592b56df"] = require("ui_HomeScreen_工坊主界面").Build,
    ["doc_60b23372"] = require("ui_OrderBoardScreen_订单板").Build,
    ["doc_b02f2da0"] = require("ui_ForgeScreen_锻造界面").Build,
    ["doc_e8b8d583"] = require("ui_ResultScreen_结算界面").Build,
    ["doc_cc38ce96"] = require("ui_UpgradeScreen_设施升级").Build,
    ["doc_8de0835c"] = require("ui_CodexScreen_名器图鉴").Build,
    ["doc_b9f9a09c"] = require("ui_StoryScreen_剧情对话").Build,
    ["doc_5c9c4e02"] = require("ui_SettingsScreen_设置").Build,
}
