-- Generated by layout-editor
return {
    ["doc_1d2e6fbf"] = require("ui_HomeScreen_工坊主界面").Build,
    ["doc_3c0047cc"] = require("ui_OrderBoardScreen_订单板").Build,
    ["doc_cf61de2e"] = require("ui_ForgeScreen_锻造界面").Build,
    ["doc_fdf5013f"] = require("ui_ResultScreen_结算界面").Build,
    ["doc_bb25af14"] = require("ui_UpgradeScreen_设施升级").Build,
    ["doc_be8fef73"] = require("ui_CodexScreen_名器图鉴").Build,
    ["doc_2696e0d2"] = require("ui_StoryScreen_剧情对话").Build,
    ["doc_dc119ed5"] = require("ui_SettingsScreen_设置").Build,
}
