-- Generated by layout-editor
---@diagnostic disable: undefined-global
local UI = require("urhox-libs/UI")
local registry = require("ui_registry")
local scene2d = require("scene2d_2D瓦片庭院")
local logic = require("logic_2D瓦片庭院")
require("urhox-libs/UI/GameHUD")

-- ────────────────────────────────────────────────────────────────────────────
-- 设计分辨率: 1190×768 | 缩放策略: MatchHeight
-- 高度精确匹配设计高，横向按比例（竖版游戏）
-- 2D 场景层 (UrhoX 原生) + UI/HUD 层共存
-- ────────────────────────────────────────────────────────────────────────────

local scene_
local cameraNode

local function firstPageBuilder()
    for _, buildFn in pairs(registry) do
        if type(buildFn) == "function" then
            return buildFn
        end
    end
    return nil
end

-- 极简 HUD 回调桥：音效经 SoundSource 播放；分数/血量/计时/胜负留空钩子，
-- 项目可按需接到具体 UI 文本节点（保留接口，避免再次出现"传 nil 全无反馈"）。
local function makeGameHud()
    return {
        OnHpChange = function(hp, maxHp) end,
        OnScoreChange = function(score) end,
        OnTimerTick = function(id, sec) end,
        OnGameOver = function(result, reason) end,
        OnPlaySound = function(sound)
            local n = scene_:CreateChild("__sfx")
            local src = n:CreateComponent("SoundSource")
            src.soundType = "Effect"
            src.autoRemoveMode = REMOVE_NODE
            local s = cache:GetResource("Sound", sound)
            if s then src:Play(s) end
        end,
    }
end

-- ── 调试日志面板（按 0 键切换显示）──
local debugLogs = {}
local debugVisible = true
local debugPanel = nil
local debugLabel = nil
local MAX_LOG_LINES = 20

local function debugLog(msg)
    table.insert(debugLogs, os.clock() and string.format("[%.1f] %s", os.clock(), tostring(msg)) or tostring(msg))
    if #debugLogs > MAX_LOG_LINES then table.remove(debugLogs, 1) end
    if debugLabel then
        debugLabel:SetText(table.concat(debugLogs, "\n"))
    end
end

local function toggleDebugPanel()
    debugVisible = not debugVisible
    if debugPanel then
        debugPanel:SetVisible(debugVisible)
    end
end

local function createDebugPanel()
    debugLabel = UI.Label {
        id = "debug_label",
        text = "-- Debug Log (press 0 to toggle) --",
        fontSize = 12,
        fontColor = "#00FF00",
    }
    debugPanel = UI.Panel {
        id = "debug_panel",
        position = "absolute",
        top = 0, left = 0,
        width = "100%", height = "60%",
        backgroundColor = "rgba(0,0,0,0.85)",
        padding = 8,
        overflow = "scroll",
        zIndex = 9999,
        children = { debugLabel },
    }
    debugPanel:SetVisible(debugVisible)
    if #debugLogs > 0 then
        debugLabel:SetText(table.concat(debugLogs, "\n"))
    end
    return debugPanel
end

function Start()
    -- ═══ 2D 场景层 ═══
    scene_ = Scene()
    scene_:CreateComponent("Octree")
    local physicsWorld = scene_:CreateComponent("PhysicsWorld2D")
    physicsWorld.gravity = Vector2(0, 0)

    -- 正交相机 + Viewport（动态 orthoSize 避免横屏黑边）
    cameraNode = scene_:CreateChild("Camera2D")
    local camera = cameraNode:CreateComponent("Camera")
    camera.orthographic = true
    -- 地图尺寸 6.4×4.16m；横屏时视野宽度不超出地图宽度
    local mapW, mapH = 6.4, 4.16
    local aspect = graphics.width / graphics.height
    camera.orthoSize = math.min(mapH, mapW / aspect)
    -- 相机初始位于地图中心，logic.UpdateCamera 会接管跟随玩家
    cameraNode.position = Vector3(mapW / 2, mapH / 2, -10)
    renderer:SetViewport(0, Viewport:new(scene_, camera))

    -- 构建 2D 场景节点 + 初始化逻辑
    local nodes = scene2d.Build(scene_)
    logic.orthoSize = camera.orthoSize
    logic.cameraNode = cameraNode

    debugLog("Scene built, orthoSize=" .. string.format("%.3f", camera.orthoSize)
        .. " children=" .. scene_:GetNumChildren(true))
    debugLog("gfx=" .. graphics.width .. "x" .. graphics.height)

    -- ═══ UI/HUD 层（叠在 2D 场景上方） ═══
    UI.Init({
        fonts = {
            { family = "sans", weights = { normal = "Fonts/MiSans-Regular.ttf" } },
        },
        scale = function() return graphics.height / 768 end,
    })
    local buildFn = firstPageBuilder()
    local rootPanel = UI.Panel {
        width = "100%", height = "100%",
        pointerEvents = "none",
        children = {
            buildFn and buildFn() or nil,
            createDebugPanel(),
        }
    }
    UI.SetRoot(rootPanel)

    -- 虚拟摇杆 + 跳跃/射击按钮（GameHUD）驱动玩家
    GameHUD.Initialize()
    local hud = GameHUD.Create({ enableJump = true, enableShooter = true })
    logic.joystick = hud.joystick
    logic.jumpButton = hud.jumpButton
    logic.shootButton = hud.shootButton or hud.fireButton

    -- HUD 回调桥
    logic.Init(scene_, nodes, makeGameHud())

    SubscribeToEvent("Update", "HandleUpdate")
    SubscribeToEvent("PhysicsBeginContact2D", "HandleBeginContact")
    SubscribeToEvent("PhysicsEndContact2D", "HandleEndContact")
end

function HandleUpdate(eventType, eventData)
    local dt = eventData["TimeStep"]:GetFloat()
    if input:GetKeyPress(KEY_0) then
        toggleDebugPanel()
    end
    logic.Update(dt)
end

function HandleBeginContact(eventType, eventData)
    local nodeA = eventData["NodeA"]:GetPtr("Node")
    local nodeB = eventData["NodeB"]:GetPtr("Node")
    local shapeA = eventData["ShapeA"]:GetPtr("CollisionShape2D")
    local shapeB = eventData["ShapeB"]:GetPtr("CollisionShape2D")
    logic.OnContact(nodeA, nodeB, shapeA, shapeB, true)
end

function HandleEndContact(eventType, eventData)
    local nodeA = eventData["NodeA"]:GetPtr("Node")
    local nodeB = eventData["NodeB"]:GetPtr("Node")
    local shapeA = eventData["ShapeA"]:GetPtr("CollisionShape2D")
    local shapeB = eventData["ShapeB"]:GetPtr("CollisionShape2D")
    logic.OnContact(nodeA, nodeB, shapeA, shapeB, false)
end

function Stop()
    UI.Shutdown()
end
