-- Generated by layout-editor
---@diagnostic disable: undefined-global, param-type-mismatch
local UI = require("urhox-libs/UI")
local registry = require("ui_registry")

-- ────────────────────────────────────────────────────────────────────────────
-- 设计分辨率: 1920×1080 | 缩放策略: MatchHeight (横屏游戏)
-- 以高度为基准，纵向精确1080；横向 baseWidth >= 1920（宽屏更宽）
-- 内容在根面板内水平居中，两侧对称留空背景色
-- ────────────────────────────────────────────────────────────────────────────

local function firstPageBuilder()
    -- 优先显示 HomeScreen
    if registry["doc_c965b15b"] then
        return registry["doc_c965b15b"]
    end
    for _, buildFn in pairs(registry) do
        if type(buildFn) == "function" then
            return buildFn
        end
    end
    return nil
end

function Start()
    UI.Init({
        fonts = {
            { family = "sans", weights = { normal = "Fonts/MiSans-Regular.ttf" } },
        },
        scale = function()
            return graphics.height / 1080
        end,
    })
    local buildFn = firstPageBuilder()
    if buildFn then
        UI.SetRoot(buildFn())
    end
end

function Stop()
    UI.Shutdown()
end
