-- Generated by layout-editor
---@diagnostic disable: undefined-global
local UI = require("urhox-libs/UI")
local registry = require("ui_registry")

-- ────────────────────────────────────────────────────────────────────────────
-- 设计分辨率: 1920×1080 | 缩放策略: MatchHeight
-- 高度精确匹配设计高，横向按比例（横版游戏宽屏适配）
-- ────────────────────────────────────────────────────────────────────────────

-- 页面列表（有序）
local pages = {}
local pageIndex = 1

function Start()
    print("[Main] Start() begin")
    UI.Init({
        fonts = {
            { family = "sans", weights = { normal = "Fonts/MiSans-Regular.ttf" } },
        },
        scale = function() return graphics.height / 1080 end,
    })
    print("[Main] UI.Init done")

    -- 收集所有页面 Build 函数
    for k, buildFn in pairs(registry) do
        if type(buildFn) == "function" then
            pages[#pages + 1] = buildFn
            print("[Main] Registered page: " .. k)
        end
    end
    print("[Main] Total pages: " .. #pages)

    if #pages > 0 then
        print("[Main] Building page 1...")
        local root = pages[1]()
        print("[Main] Page 1 built, calling SetRoot...")
        UI.SetRoot(root)
        print("[Main] Loaded page 1/" .. #pages .. " (LEFT/RIGHT to switch)")
    end

    SubscribeToEvent("KeyUp", "HandleKeyUp")
end

---@param eventType string
---@param eventData KeyUpEventData
function HandleKeyUp(eventType, eventData)
    local key = eventData["Key"]:GetInt()

    if key == KEY_RIGHT then
        pageIndex = pageIndex + 1
        if pageIndex > #pages then pageIndex = 1 end
        UI.SetRoot(pages[pageIndex]())
        print("[Main] Page " .. pageIndex .. "/" .. #pages)
    elseif key == KEY_LEFT then
        pageIndex = pageIndex - 1
        if pageIndex < 1 then pageIndex = #pages end
        UI.SetRoot(pages[pageIndex]())
        print("[Main] Page " .. pageIndex .. "/" .. #pages)
    end
end

function Stop()
    UI.Shutdown()
end
