-- ============================================================================
-- 2D瓦片庭院 - SCE/TapTap Lua export
-- module: ui_2D瓦片庭院
-- layout mode: responsive (100% width/height)
-- 建议 screen_orientation: landscape
-- Generated by layout-editor
-- Props 已移至 scene2d 用 StaticSprite2D + textureRect 渲染（UI backgroundImage 无法正确裁剪）
-- ============================================================================

local UI = require("urhox-libs/UI")

local M = {}

M.Actions = {
}

function M.Build(payload)
    payload = payload or {}
    return UI.Panel {
            id = "gamescene2d_rqh2jua7",
            width = "100%",
            height = "100%",
            position = "relative",
            pointerEvents = "none",
            children = {
                UI.Label {
                    id = "text_cfssj1ch",
                    text = "TileMap2D 顶视庭院",
                    position = "absolute",
                    left = 16.39,
                    top = 12.29,
                    fontSize = 13.31,
                    fontWeight = 700,
                    fontColor = "#bef264",
                },
            },
        }
end

return M
