-- Generated by layout-editor
return {
    ["doc_c965b15b"] = require("ui_HomeScreen_工坊主界面").Build,
---@diagnostic disable: param-type-mismatch
    ["doc_5076e7d0"] = require("ui_OrderBoardScreen_订单板").Build,
    ["doc_9a02e49a"] = require("ui_ForgeScreen_锻造界面").Build,
    ["doc_6b7a2240"] = require("ui_ResultScreen_结算界面").Build,
    ["doc_ae2441b2"] = require("ui_UpgradeScreen_设施升级").Build,
    ["doc_a01abc1a"] = require("ui_CodexScreen_名器图鉴").Build,
    ["doc_f0ef6e26"] = require("ui_StoryScreen_剧情对话").Build,
    ["doc_3b4d6c67"] = require("ui_SettingsScreen_设置").Build,
}
