-- ============================================================================
-- StoryScreen_剧情对话 - SCE/TapTap Lua export
-- module: ui_StoryScreen_剧情对话
---@diagnostic disable: param-type-mismatch
-- layout mode: responsive (100% width/height)
-- 建议 screen_orientation: landscape
-- Generated by layout-editor
-- ============================================================================

local UI = require("urhox-libs/UI")

local M = {}

M.Actions = {
}

function M.Build(payload)
    payload = payload or {}
    return UI.Panel {
            id = "root",
            width = "100%",
            height = "100%",
            backgroundColor = "#1f1a17",
            children = {
                -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                UI.Panel {
                    id = "sr_0",
                    position = "absolute",
                    width = "100%",
                    height = "100%",
                    backgroundColor = "#1F1A17",
                },
                UI.Panel {
                    id = "ph_1",
                    position = "absolute",
                    width = "100%",
                    height = "100%",
                    backgroundColor = "#00000000",
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_2",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            backgroundColor = "rgba(15,12,10,0.95)",
                            borderColor = "transparent",
                            borderWidth = 2,
                        },
                        -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sl_3",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            display = "none",
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sl_3__placeholder",
                                    text = "[!] ShapeLine",
                                    fontSize = 11,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                        -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sl_4",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            display = "none",
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sl_4__placeholder",
                                    text = "[!] ShapeLine",
                                    fontSize = 11,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                        UI.Label {
                            id = "tx_5",
                            text = "【剧情场景占位】铁匠铺夜景 · 烛火 · 雨檐 · 远山",
                            position = "absolute",
                            left = 0,
                            top = 525.68,
                            width = 1920,
                            height = 28.11,
                            fontSize = 19.68,
                            fontWeight = 400,
                            textAlign = "left",
                            lineHeight = 1.016,
                            fontColor = "#f7e8c866",
                            verticalAlign = "top",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_6",
                    position = "absolute",
                    left = "5.86%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_6__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_7",
                    position = "absolute",
                    left = "13.18%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_7__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_8",
                    position = "absolute",
                    left = "20.50%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_8__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_9",
                    position = "absolute",
                    left = "27.82%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_9__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_a",
                    position = "absolute",
                    left = "35.14%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_a__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_b",
                    position = "absolute",
                    left = "42.46%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_b__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_c",
                    position = "absolute",
                    left = "49.78%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_c__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_d",
                    position = "absolute",
                    left = "57.10%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_d__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_e",
                    position = "absolute",
                    left = "64.42%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_e__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_f",
                    position = "absolute",
                    left = "71.74%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_f__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_g",
                    position = "absolute",
                    left = "79.06%",
                    width = 28.11,
                    height = "100%",
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_g__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_h",
                    position = "absolute",
                    width = 28.11,
                    height = "100%",
                    right = 233,
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_h__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 11,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                UI.Panel {
                    id = "ph_i",
                    position = "absolute",
                    left = "4.38%",
                    top = "13.06%",
                    width = 514,
                    height = 568,
                    backgroundColor = "#00000000",
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_j",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            height = 570,
                            right = 8,
                            backgroundColor = "rgba(31,26,23,0.85)",
                            borderRadius = 8,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_m",
                            text = "【立绘 · 老师傅】\n抱铁拳 · 围裙 · 烟斗",
                            position = "absolute",
                            left = 0,
                            top = 371.07,
                            width = 506,
                            fontSize = 22.49,
                            fontWeight = 400,
                            textAlign = "center",
                            lineHeight = 0.889,
                            fontColor = "#c9a45a",
                            verticalAlign = "middle",
                        },
                    },
                },
                -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                UI.Panel {
                    id = "sr_n",
                    position = "absolute",
                    left = "2.93%",
                    width = 393.56,
                    height = 50.6,
                    display = "none",
                    bottom = 132,
                    backgroundColor = "#3A322B",
                    borderRadius = 6,
                    borderColor = "#C9A45A",
                    borderWidth = 2,
                },
                UI.Label {
                    id = "tx_o",
                    text = "· 老 · 钟 · ",
                    position = "absolute",
                    left = "2.93%",
                    top = 896.75,
                    width = 393.56,
                    height = 50.6,
                    fontSize = 25.3,
                    fontWeight = 700,
                    textAlign = "left",
                    lineHeight = 1.423,
                    fontColor = "#c9a45a",
                    verticalAlign = "top",
                },
                UI.Label {
                    id = "tx_p",
                    text = "北街铁匠铺  ·  你师父",
                    position = "absolute",
                    left = "2.93%",
                    top = 952.97,
                    width = 393.56,
                    height = 25.3,
                    fontSize = 15.46,
                    fontWeight = 400,
                    textAlign = "left",
                    lineHeight = 1.164,
                    fontColor = "#f7e8c899",
                    verticalAlign = "top",
                },
                UI.Panel {
                    id = "df_q",
                    position = "absolute",
                    top = "13.02%",
                    width = 393.56,
                    height = 281.11,
                    backgroundColor = "#00000000",
                    right = 56,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_r",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            backgroundColor = "rgba(31,26,23,0.85)",
                            borderRadius = 4,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        -- [!] ShapeCircle 包含 1 条 draw 命令 (circle)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sc_s",
                            position = "absolute",
                            left = "2.14%",
                            top = "3.00%",
                            width = 8.43,
                            height = 8.43,
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sc_s__placeholder",
                                    text = "[!] ShapeCircle",
                                    fontSize = 5,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                        -- [!] ShapeCircle 包含 1 条 draw 命令 (circle)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sc_t",
                            position = "absolute",
                            top = "3.00%",
                            width = 8.43,
                            height = 8.43,
                            right = 8,
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sc_t__placeholder",
                                    text = "[!] ShapeCircle",
                                    fontSize = 5,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                        -- [!] ShapeCircle 包含 1 条 draw 命令 (circle)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sc_u",
                            position = "absolute",
                            left = "2.14%",
                            width = 8.43,
                            height = 8.43,
                            bottom = 8,
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sc_u__placeholder",
                                    text = "[!] ShapeCircle",
                                    fontSize = 5,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                        -- [!] ShapeCircle 包含 1 条 draw 命令 (circle)。
                        -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                        -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                        UI.Panel {
                            id = "sc_v",
                            position = "absolute",
                            width = 8.43,
                            height = 8.43,
                            right = 8,
                            bottom = 8,
                            borderRadius = 4,
                            borderColor = "#a78bfa",
                            borderWidth = 1,
                            overflow = "hidden",
                            children = {
                                UI.Label {
                                    id = "sc_v__placeholder",
                                    text = "[!] ShapeCircle",
                                    fontSize = 5,
                                    fontColor = {
                                        167,
                                        139,
                                        250,
                                        255,
                                    },
                                    textAlign = "center",
                                    verticalAlign = "middle",
                                    width = "100%",
                                    height = "100%",
                                },
                            },
                        },
                    },
                },
                UI.Label {
                    id = "tx_w",
                    text = "· 章节 · 一章·三幕 ·",
                    position = "absolute",
                    left = 1492.71,
                    top = 163.05,
                    width = 348.58,
                    height = 30.92,
                    fontSize = 19.68,
                    fontWeight = 700,
                    textAlign = "left",
                    lineHeight = 1.118,
                    fontColor = "#c9a45a",
                    verticalAlign = "top",
                },
                -- [!] ShapeLine 包含 1 条 draw 命令 (line)。
                -- urhox-libs/UI 没有 render(self, canvas) 协议和等价的 canvas 绘图 API。
                -- 如需在真机渲染这些图形，请改用 backgroundColor + borderRadius + borderColor 表达，或在 Lua 层手写 NanoVG 调用。
                UI.Panel {
                    id = "sl_x",
                    position = "absolute",
                    top = "18.75%",
                    width = 348.58,
                    height = 2.81,
                    right = 79,
                    borderRadius = 4,
                    borderColor = "#a78bfa",
                    borderWidth = 1,
                    overflow = "hidden",
                    children = {
                        UI.Label {
                            id = "sl_x__placeholder",
                            text = "[!] ShapeLine",
                            fontSize = 4,
                            fontColor = {
                                167,
                                139,
                                250,
                                255,
                            },
                            textAlign = "center",
                            verticalAlign = "middle",
                            width = "100%",
                            height = "100%",
                        },
                    },
                },
                UI.Label {
                    id = "tx_y",
                    text = "入门徒之夜\n师父交付头一道委托\n选择关乎名声的初印象",
                    position = "absolute",
                    left = 1492.71,
                    top = 216.46,
                    width = 348.58,
                    height = 140.56,
                    fontSize = 16.87,
                    fontWeight = 400,
                    textAlign = "left",
                    lineHeight = 1.186,
                    fontColor = "#f1e5cc",
                    verticalAlign = "top",
                },
                -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                UI.Panel {
                    id = "sr_z",
                    position = "absolute",
                    left = 56,
                    height = 309.22,
                    right = 56,
                    bottom = 28,
                    backgroundColor = "rgba(15,12,10,0.92)",
                    borderRadius = 10,
                    borderColor = "#C9A45A",
                    borderWidth = 3,
                },
                -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                UI.Panel {
                    id = "sr_10",
                    position = "absolute",
                    left = "4.39%",
                    top = "69.53%",
                    width = 224.89,
                    height = 44.98,
                    backgroundColor = "#C96A2B",
                    borderRadius = 4,
                    borderColor = "#C9A45A",
                    borderWidth = 1,
                },
                UI.Label {
                    id = "tx_11",
                    text = "老钟",
                    position = "absolute",
                    left = 84.33,
                    top = 750.57,
                    width = 224.89,
                    height = 44.98,
                    fontSize = 19.68,
                    fontWeight = 700,
                    textAlign = "left",
                    lineHeight = 1.626,
                    fontColor = "#f1e5cc",
                    verticalAlign = "top",
                },
                UI.Label {
                    id = "tx_12",
                    text = "\"小子，柳七娘的剪子今晚要交。\n手里的料是寒铁配银线钢，文火慢锻，莫贪求出尘。\n她要的是 平日好用，不是镇山之宝。听明白了？\"",
                    position = "absolute",
                    left = "4.39%",
                    top = 803.98,
                    width = 1723.22,
                    height = 98.39,
                    fontSize = 22.49,
                    fontWeight = 400,
                    textAlign = "left",
                    lineHeight = 1.067,
                    fontColor = "#f1e5cc",
                    verticalAlign = "top",
                },
                UI.Panel {
                    id = "plate_13",
                    position = "absolute",
                    left = "4.39%",
                    width = 413.94,
                    height = 112.45,
                    backgroundColor = "#00000000",
                    bottom = 51,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_14",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            backgroundColor = "rgba(79,122,99,0.85)",
                            borderRadius = 8,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_15",
                            text = "\"我懂——应了。\"",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 413.94,
                            height = 112.45,
                            fontSize = 18.27,
                            fontWeight = 700,
                            textAlign = "center",
                            fontColor = "#f1e5cc",
                            verticalAlign = "middle",
                        },
                    },
                },
                UI.Panel {
                    id = "plate_16",
                    position = "absolute",
                    left = "26.83%",
                    width = 413.94,
                    height = 112.45,
                    backgroundColor = "#00000000",
                    bottom = 51,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_17",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            borderRadius = 8,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_18",
                            text = "\"师父，能不能再讲一遍？\"",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 413.94,
                            height = 112.45,
                            fontSize = 18.27,
                            fontWeight = 700,
                            textAlign = "center",
                            fontColor = "#c9a45a",
                            verticalAlign = "middle",
                        },
                    },
                },
                UI.Panel {
                    id = "plate_19",
                    position = "absolute",
                    left = "49.27%",
                    width = 413.94,
                    height = 112.45,
                    backgroundColor = "#00000000",
                    bottom = 51,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_1a",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            borderRadius = 8,
                            borderColor = "#C96A2B",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_1b",
                            text = "\"我能不能用更好的料？\"",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 413.94,
                            height = 112.45,
                            fontSize = 18.27,
                            fontWeight = 700,
                            textAlign = "center",
                            fontColor = "#c96a2b",
                            verticalAlign = "middle",
                        },
                    },
                },
                UI.Panel {
                    id = "plate_1c",
                    position = "absolute",
                    width = 413.94,
                    height = 112.45,
                    backgroundColor = "#00000000",
                    right = 129,
                    bottom = 51,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_1d",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            backgroundColor = "rgba(138,61,46,0.55)",
                            borderRadius = 8,
                            borderColor = "#3A322B",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_1e",
                            text = "【沉默】（点头）",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 413.94,
                            height = 112.45,
                            fontSize = 18.27,
                            fontWeight = 700,
                            textAlign = "center",
                            fontColor = "#f1e5cc",
                            verticalAlign = "middle",
                        },
                    },
                },
                UI.Panel {
                    id = "plate_1f",
                    position = "absolute",
                    top = "2.08%",
                    width = 112.45,
                    height = 39.36,
                    backgroundColor = "#00000000",
                    right = 169,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_1g",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            borderRadius = 14,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_1h",
                            text = "跳过",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 112.45,
                            height = 39.36,
                            fontSize = 16.87,
                            fontWeight = 700,
                            textAlign = "center",
                            lineHeight = 1.66,
                            fontColor = "#c9a45a",
                            verticalAlign = "middle",
                        },
                    },
                },
                UI.Panel {
                    id = "plate_1i",
                    position = "absolute",
                    top = "2.08%",
                    width = 126.5,
                    height = 39.36,
                    backgroundColor = "#00000000",
                    right = 28,
                    children = {
                        -- ShapeRect: 退化为标准 UI.Panel（fill/stroke/radius 已平铺到容器属性）
                        UI.Panel {
                            id = "sr_1j",
                            position = "absolute",
                            width = "100%",
                            height = "100%",
                            borderRadius = 14,
                            borderColor = "#C9A45A",
                            borderWidth = 2,
                        },
                        UI.Label {
                            id = "tx_1k",
                            text = "返回",
                            position = "absolute",
                            left = 0,
                            top = 0,
                            width = 126.5,
                            height = 39.36,
                            fontSize = 16.87,
                            fontWeight = 700,
                            textAlign = "center",
                            lineHeight = 1.66,
                            fontColor = "#c9a45a",
                            verticalAlign = "middle",
                        },
                    },
                },
            },
        }
end

return M
